language: go

go:
  - 1.x
  - "1.10"
  - 1.11.x
  - 1.12

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  except:
    - develop
  only:
    - master
